version: "3.9"

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  web:
    build: .
    tty: true
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
