version: "3.9"

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    env_file:
      - .env
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./nginx/templates/nginx.conf:/etc/nginx/templates
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT}
    depends_on:
      - web
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  web:
    build: .
    tty: true
    volumes:
      - nginx-shared:${DOCKER_NGINX_VOLUME_ROOT}
    env_file:
      - .env
    depends_on:
      - db
